### PR TITLE
Add Scala 2.12.0-M2 as a cross build

### PR DESCRIPTION
**Pull request by retronym**

### CODE REVIEW

**Comment by retronym** [comment]
Review by @rkuhn or @viktorklang

**Comment by retronym** [comment]
Marking as "on-hold" as this would prevent #50

**Comment by viktorklang** [comment]
@retronym The reason for final-ing DefaultPromise is to make sure that the optimizer can do its job, avoiding tripping into bimorphic or megamorphic callsites. I think the extra allocation and indirection in your proposal is OK given that, but also to prevent others from extending it. Wdyt?

**Comment by retronym** [comment]
@viktorklang Can you see a way to implement #50 if `DefaultPromise` if final? The only solution I see is to copy/paste its implementation.

**Comment by retronym** [comment]
We could mark a selection of methods like `isCompleted` and `value` as final `DefaultPromise` to keep them bimorphic (`KeptPromise` also implements them).

**Comment by viktorklang** [comment]
@retronym Perhaps an option would be to make all of the methods on DefaultPromise final?

**Comment by retronym** [comment]
Yeah, I'm fine with that.

**Comment by viktorklang** [comment]
@retronym We also need to audit the methods to make sure that nothing will break (is there something that assumes no inheritance?) as well as make sure that methods that may have harmful effects if called from inheriters(?) will be either hidden or appropriately documented.

**Comment by retronym** [comment]
Yep, changing modifiers is subtle. Could you review your addition of the finality to confirm it was done solely for non functional reasons?

**Comment by retronym** [comment]
I don't think we need to lock it down to much as it is the whole class already access restricted. If someone plays a trick to subvert that (as we do here) we assume they are responsible for the consequences

**Comment by viktorklang** [comment]
I can review the addition at the earliest next week :/

**Comment by 2m** [comment]
Released latest genjavadoc (which is `0.9`) for scala 2.12.0-M2. Can you update to 0.9 and keep the build clean of scala version switch statements? :) I tried it locally and there seems to be no problems when using `0.9`.

**Comment by retronym** [comment]
ping @viktorklang for assessment on the impact of unfinalizing `DefaultPromise`.

**Comment by retronym** [comment]
@2m Thanks for that. I've updated this PR to use 0.9 of genjavadoc in both 2.11 and 2.12.

**Comment by viktorklang** [comment]
@retronym I only had time for a cursory overview, it seems as unfinalizing it will be fine. May be in order to final-ize all of its methods tho.

**Pull request merged**
