### PR TITLE
add [oraclejdk10] to Travis CI

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by SethTisue** [comment]
`[error] javadoc: error - invalid flag: -d`, I guess something has changed there?

**Comment by xuwei-k** [comment]
> [error] javadoc: error - invalid flag: -d, I guess something has changed there?

https://github.com/sbt/sbt/issues/4350

**Comment by SethTisue** [comment]
not sure what to do about this, except maybe wait for the sbt fix to land in sbt 1.3

**Comment by SethTisue** [comment]
happened at https://github.com/scala/scala-java8-compat/pull/129 as well, so using JDK 11 instead of 10 doesn't help

in the Scala 2.12 JDK 11 community build, we work around it with `set publishArtifact in packageDoc := false`, we could do that here as well I guess :-/

**Comment by SethTisue** [comment]
also I see, just now, that our `build.sbt` provides `disableDocs`

**Comment by SethTisue** [comment]
closing this PR since JDK 10 is obsolete anyway; but I opened #130

**Comment by SethTisue** [comment]
fresh attempt: https://github.com/scala/scala-java8-compat/pull/135

**Pull request closed without merging**
